apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: sampleapi
  template:
    metadata:
      labels:
        k8s-app: sampleapi
      name: sampleapi
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: http
        name: sampleapi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: appsettings-volume
          readOnly: true
          subPath: appsettings.json
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      volumes:
      - name: appsettings-volume
        secret:
          secretName: sampleapisecrets
