apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: sampleapi
  template:
    metadata:
      labels:
        k8s-app: sampleapi
      name: sampleapi
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
